<a href="https://colab.research.google.com/github/chien2734/sgu_data_analyst/blob/anh/A_3_v%C3%A0_A_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# TẠO MẢNG DỮ LIỆU VÍ DỤ 4x3
arr = np.array([
    [10., 15., 20.],
    [ 2.,  4.,  6.],
    [ 7.,  8.,  9.],
    [ 1.,  3.,  5.]
])

# BƯỚC 1: TÍNH TRUNG BÌNH THEO HÀNG (AXIS=1)
row_means = arr.mean(axis=1) # [15., 4., 8., 3.]

# BƯỚC 2: CHÈN TRỤC MỚI (RESHAPE) ĐỂ BROADCAST
row_means_reshaped = row_means.reshape((4, 1))

# BƯỚC 3: TRỪ VÀ THỰC HIỆN DEMEANING
demeaned_rows = arr - row_means_reshaped

print("Mảng Gốc:\n", arr)
print("\nTrung bình Hàng (Reshaped):\n", row_means_reshaped)
print("\nKết quả Demeaning (Kiểm tra: Tổng trung bình mỗi hàng = 0):\n", demeaned_rows)
print("\nKiểm tra trung bình hàng mới:\n", demeaned_rows.mean(axis=1))

Mảng Gốc:
 [[10. 15. 20.]
 [ 2.  4.  6.]
 [ 7.  8.  9.]
 [ 1.  3.  5.]]

Trung bình Hàng (Reshaped):
 [[15.]
 [ 4.]
 [ 8.]
 [ 3.]]

Kết quả Demeaning (Kiểm tra: Tổng trung bình mỗi hàng = 0):
 [[-5.  0.  5.]
 [-2.  0.  2.]
 [-1.  0.  1.]
 [-2.  0.  2.]]

Kiểm tra trung bình hàng mới:
 [0. 0. 0. 0.]


In [ ]:
# MẢNG VÍ DỤ
sequence = np.arange(1, 6) # [1, 2, 3, 4, 5]

# 1. reduce (Tổng hợp cuối cùng)
sum_reduce = np.add.reduce(sequence)

# 2. accumulate (Tổng hợp tích lũy)
sum_accumulate = np.add.accumulate(sequence)

print("np.add.reduce (Tổng):", sum_reduce)
print("np.add.accumulate (Tổng tích lũy):", sum_accumulate)

np.add.reduce (Tổng): 15
np.add.accumulate (Tổng tích lũy): [ 1  3  6 10 15]


In [ ]:
# MẢNG VÍ DỤ
arr_a = np.array([2, 5])
arr_b = np.array([10, 20, 30])

# 1. outer (Tích Ngoài)
# Kết quả: arr_a[i] * arr_b[j]
cross_product_outer = np.multiply.outer(arr_a, arr_b)

print("\nTích Ngoài (Outer Product):\n", cross_product_outer)

# 2. reduceat (Tổng hợp cục bộ/Group By)
arr_data = np.arange(10)
# Điểm cắt: [0, 5, 8] -> Tổng trên các đoạn [0:5], [5:8], [8:]
bins = [0, 5, 8]
local_sum = np.add.reduceat(arr_data, bins)

print("\nKết quả reduceat (Tổng cục bộ):", local_sum)


Tích Ngoài (Outer Product):
 [[ 20  40  60]
 [ 50 100 150]]

Kết quả reduceat (Tổng cục bộ): [10 18 17]
