<a href="https://colab.research.google.com/github/chien2734/sgu_data_analyst/blob/main/Personal/%5BBOOK%5D_Python_for_DataAnalyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> CHAPTER 1: Prelininaries


## 1.1 What Is This Book About?



## 1.2 Why Python for Data Analysis?

## 1.3 Essential Python Libraries

## 1.4 Installation and Setup

## 1.5 Community and Conferences

## 1.6 Navigating This Book

In [ ]:
import numpy as np
import pandas as pd
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

In [ ]:
#Import Conventions
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm

<h1> CHAPTER 2:
Python Language Basics, IPython,
and Jupyter Notebooks

## 2.1 The Python Interpreter

In [ ]:
a = 5
print(a)

print("Hello world")

5
Hello world


## 2.2 IPython Basics

### Running the IPython Shell

In [ ]:
a = 5
a #print 5

5

In [ ]:
import numpy as np
data = [np.random.standard_normal() for i in range(8)]
data #print(data)

[-0.04664350085945034,
 0.08334126223593778,
 0.044577390567203785,
 -0.07512381189122282,
 -2.538163815938322,
 0.3652711235795394,
 -1.6728013983197745,
 1.6451020548688982]

### Running the Jupyter Notebook

### Tab Completion

In [ ]:
an_apple = 27
an_example = 42
an_apple

b = [1, 2, 3]
b.append

import datetime
datetime.datetime.now()


None


datetime.datetime(2025, 10, 13, 5, 43, 16, 140007)

### Introspection

Using a question mark (?) before or after a variable will display some general infor‐
mation about the object:

In [ ]:
b = [1, 2, 3]
b?

print?
# Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
# Docstring:
# Prints the values to a stream, or to sys.stdout by default.

In [ ]:
def add_numbers(a, b):
  """
  Add two numbers together
  Returns
  -------
  the_sum : type of arguments
  """
  return a + b

add_numbers?
# Signature: add_numbers(a, b)
# Docstring:
# Add two numbers together
# Returns

In [ ]:
import numpy as np
np.*load*?
# np.__loader__
# np.load
# np.loadtxt

## 2.3 Python Language Basics

### Language Semantics

#### Indentation, not braces

In [ ]:
for x in array:
  if x < pivot:
    less.append(x)
  else:
    greater.append(x)

a = 5; b = 6; c = 7

#### Comment

In [ ]:
results = []
for line in file_handle:
  # keep the empty lines for now
  # if len(line) == 0:
  # continue
  results.append(line.replace("foo", "bar"))

print("Reached this line") # Simple status report

#### Function and object method calls

In [ ]:
result = f(x, y, z)
g()

obj.some_method(x, y, z)

result = f(a, b, c, d=5, e="foo")

#### Variables and argument passing

In [ ]:
a = [1, 2, 3]
b = a
a.append(4)
print(b)

def append_element(some_list, element):
  some_list.append(element)
#Then we have:
data = [1, 2, 3]
append_element(data, 4)
data


[1, 2, 3, 4]


[1, 2, 3, 4]

#### Dynamic references, strong types

In [ ]:
a = 5
print(type(a)) # int
a = "foo"
print(type(a)) # str

#"5" + 5 # Error

a = 4.5
b = 2
# String formatting, to be visited later
print(f"a is {type(a)}, b is {type(b)}")
a / b

<class 'int'>
<class 'str'>
a is <class 'float'>, b is <class 'int'>


2.25

In [ ]:
a = 5
print(isinstance(a, int))

a = 5; b = 4.5
print(isinstance(a, (int, float)))
print(isinstance(b, (int, float)))

True
True
True


#### Attributes and methods

In [ ]:
a = "foo"
getattr(a, "split")

<function str.split(sep=None, maxsplit=-1)>

#### Duck typing

In [ ]:
def isiterable(obj):
  try:
    iter(obj)
    return True
  except TypeError: # not iterable
    return False

In [ ]:
isiterable("a string") #True
isiterable([1, 2, 3]) #True
isiterable(5) #False

False

#### Imports

In [ ]:
import some_module
result = some_module.f(5)
pi = some_module.PI
#Or alternately:
from some_module import g, PI
result = g(5, PI)
#By using the as keyword, you can give imports different variable names:
import some_module as sm
from some_module import PI as pi, g as gf
r1 = sm.f(pi)
r2 = gf(6, pi)

#### Binary operators and comparisons

In [ ]:
print(5 - 7)
print(12 + 21.5)
print(5 <= 2)
a = [1, 2, 3]
b = a
c = list(a)
print(a is b)
print(a is not c)
print(a==c)
a = None
print(a is None)

-2
33.5
False
True
True
True
True


#### Mutable and immutable objects

In [ ]:
a_list = ["foo", 2, [4, 5]]
a_list[2] = (3, 4)
a_list
a_tuple = (3, 5, (4, 5))
a_tuple[1] = "four"
#'tuple' object does not support item assignment

['foo', 2, (3, 4)]

### Scalar Types

#### Numeric types

In [ ]:
ival = 17239871
print(ival**6)

fval = 7.243
fval2 = 6.78e-5

print(3/2)
print(3//2)

26254519291092456596965462913230729701102721
1.5
1


#### Strings

In [ ]:
a = 'this is a string'
b = "another way"
c = """
This is a longer string that
spans multiple lines
"""

print(c.count("\n"))

#a[10] ="f"
#'str' object does not support item assignment

b = a.replace("string", "longer string")
print(b)
print(a)

a = 5.6
s=str(a)
print(s)

s = "python"
print(list(s))
print(s[:3])

s = "12\\34"
print(s)

s = r"this\has\no\special\characters"
print(s)

a = "this is the first half "
b = "and this is the second half"
print(a + b)

template = "{0:.2f} {1:s} are worth US${2:d}"

print(template.format(88.46, "Argentine Pesos", 1))

amount = 10
rate = 88.46
currency = "Pesos"
result = f"{amount} {currency} is worth US${amount / rate}"
f"{amount} {currency} is worth US${amount / rate:.2f}"

3
this is a longer string
this is a string
5.6
['p', 'y', 't', 'h', 'o', 'n']
pyt
12\34
this\has\no\special\characters
this is the first half and this is the second half
88.46 Argentine Pesos are worth US$1


'10 Pesos is worth US$0.11'

#### Bytes and Unicode


In [ ]:
val = "español"
print(val)

val_utf8 = val.encode("utf-8")
print(val_utf8)

print(type(val_utf8))
print(val_utf8.decode("utf-8"))

print(val.encode("latin1"))
print(val.encode("utf-16"))
print(val.encode("utf-16le"))

español
b'espa\xc3\xb1ol'
<class 'bytes'>
español
b'espa\xf1ol'
b'\xff\xfee\x00s\x00p\x00a\x00\xf1\x00o\x00l\x00'
b'e\x00s\x00p\x00a\x00\xf1\x00o\x00l\x00'


#### Booleans

In [ ]:
print(True and True)
print(False or True)
print(int(False))
print(int(True))
a = True
b = False
print(not a)
print( not b)

True
True
0
1
False
True


#### Type casting

In [ ]:
s = "3.14159"
fval = float(s)
print(type(fval))
print(int(fval))
print(bool(fval))
print(bool(0))

<class 'float'>
3
True
False


#### None

In [ ]:
a = None
print(a is None)
b = 5
print(b is not None)

True
True


In [ ]:
def add_and_maybe_multiply(a, b, c=None):
  result = a + b
  if c is not None:
    result = result * c
  return result
print(add_and_maybe_multiply(1, 2))
add_and_maybe_multiply(1, 2, 3)


3


9

#### Dates and times

In [ ]:
from datetime import datetime, date, time
dt = datetime(2011, 10, 29, 20, 30, 21)
print(dt.day)
print(dt.minute)

print(dt.date())
print(dt.time())

print(dt.strftime("%Y-%m-%d %H:%M"))
print(datetime.strptime("20091031", "%Y%m%d"))

dt_hour = dt.replace(minute=0, second=0)
print(dt_hour)
print(dt)

29
30
2011-10-29
20:30:21
2011-10-29 20:30
2009-10-31 00:00:00
2011-10-29 20:00:00
2011-10-29 20:30:21


In [ ]:
dt2 = datetime(2011, 11, 15, 22, 30)
delta = dt2 - dt
print(delta)
print(type(delta))
print(dt)
print(dt + delta)

17 days, 1:59:39
<class 'datetime.timedelta'>
2011-10-29 20:30:21
2011-11-15 22:30:00


### Control Flow

#### if, elif, and else

In [ ]:
x = -5
if x < 0:
  print("It's negative")

It's negative


In [ ]:
if x < 0:
  print("It's negative")
elif x == 0:
  print("Equal to zero")
elif 0 < x < 5:
  print("Positive but smaller than 5")
else:
  print("Positive and larger than or equal to 5")

It's negative


In [ ]:
a = 5; b = 7
c = 8; d = 4
if a < b or c > d:
  print("Made it")

Made it


In [ ]:
4 > 3 > 2 < 1

False

#### for loops

In [ ]:
sequence = [1, 2, None, 4, None, 5]
total = 0
for value in sequence:
  if value is None:
    continue
  total += value
print(total)

12


In [ ]:
sequence = [1, 2, 0, 4, 6, 5, 2, 1]
total_until_5 = 0
for value in sequence:
  if value == 5:
    break
  total_until_5 += value
print(total_until_5)

13


In [ ]:
for i in range(4):
   for j in range(4):
    if j > i:
      break
    print((i, j))

(0, 0)
(1, 0)
(1, 1)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


#### while loops

In [ ]:
x = 256
total = 0
while x > 0:
  if total > 500:
    break
  total += x
  x = x // 2
print(total)

504


#### pass

In [ ]:
if x < 0:
  print("negative!")
elif x == 0:
# TODO: put something smart here
  pass
else:
  print("positive!")

positive!


#### range

In [ ]:
print(range(10))
print(list(range(10)))
print(list(range(0, 20, 2)))
print(list(range(5, 0, -1)))

seq = [1, 2, 3, 4]
for i in range(len(seq)):
  print(f"element {i}: {seq[i]}")

total = 0
for i in range(100_000):
   # % is the modulo operator
   if i % 3 == 0 or i % 5 == 0:
    total += i
print(total)

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[5, 4, 3, 2, 1]
element 0: 1
element 1: 2
element 2: 3
element 3: 4
2333316668


## 2.4 Conclusion

# CHAPTER 3: Built-In Data Structures Functions, and Files

## 3.1 Data Structures and Sequences

### Tuple
A tuple is a fixed-length, immutable sequence of Python objects which, once assigned,
cannot be changed.

In [1]:
tup = (4, 5, 6)
print(tup)

(4, 5, 6)


In [2]:
tup = 1, 2, 3
tup

(1, 2, 3)

In [5]:
tuple([4, 0, 3])

(4, 0, 3)

In [7]:
tup = tuple('Bui Duc Chien')
tup

('B', 'u', 'i', ' ', 'D', 'u', 'c', ' ', 'C', 'h', 'i', 'e', 'n')

In [8]:
tup[0]

'B'

In [9]:
nested_tup = (4, 5, 6), (7, 8)
nested_tup

((4, 5, 6), (7, 8))

In [11]:
print(nested_tup[0])
print(nested_tup[1])

(4, 5, 6)
(7, 8)


In [16]:
tup = tuple(['foo', [1, 2], True])
tup[2] = False

TypeError: 'tuple' object does not support item assignment

In [17]:
tup[1].append(3)
tup

('foo', [1, 2, 3], True)

In [18]:
(4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [19]:
('foo', 'bar') * 4

('foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'bar')

#### Unpacking tuples
If you try to assign to a tuple-like expression of variables, Python will attempt to
unpack the value on the righthand side of the equals sign:

In [21]:
tup = (4, 5, 6)
a, b, c = tup
c

6

In [22]:
tup = 4, 5, (6, 7)
a, b, (c, d) = tup
d

7

In [24]:
a, b = 1, 2
print("Before: a = ", a)
print("Before: b = ", b)
#swap
b, a = a, b
print("After: a = ", a)
print("After: b = ", b)

Before: a =  1
Before: b =  2
After: a =  2
After: b =  1


In [25]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
for a, b, c in seq:
  print(f"a={a}, b={b}, c={c}")
#

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [26]:
values = 1, 2, 3, 4, 5
a, b, *rest = values
print(a, b)
print(rest)

1 2
[3, 4, 5]


In [29]:
a, b, *_ = values
_

[3, 4, 5]

#### Tuple methods
Since the size and contents of a tuple cannot be modified, it is very light on instance
methods.

In [30]:
a = (1, 2, 2, 2, 3, 4, 2)
a.count(2)

4

### List
In contrast with tuples, lists are variable length and their contents can be modified in
place. Lists are mutable. You can define them using square brackets [] or using the
list type function:

In [40]:
a_list = [2, 3, 7, None]
tup = ("foo", "bar", "baz")
b_list = list(tup)
b_list

['foo', 'bar', 'baz']

In [41]:
b_list[1] = "peekaboo"
b_list

['foo', 'peekaboo', 'baz']

In [42]:
gen = range(10)
print(gen)
list(gen)

range(0, 10)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Adding and removing elements

In [43]:
b_list.append("dwarf")
b_list

['foo', 'peekaboo', 'baz', 'dwarf']

In [44]:
b_list.insert(1, "red")
b_list

['foo', 'red', 'peekaboo', 'baz', 'dwarf']

In [45]:
print(b_list.pop(2))
b_list

peekaboo


['foo', 'red', 'baz', 'dwarf']

In [46]:
b_list.append("foo")
b_list

['foo', 'red', 'baz', 'dwarf', 'foo']

In [47]:
b_list.remove("foo")
b_list

['red', 'baz', 'dwarf', 'foo']

Check if a list contains a value

In [48]:
"dwarf" in b_list

True

In [50]:
"dwarf" not in b_list

False

#### Concatenating and combining lists

In [51]:
#Similar to tuples, adding two lists together with + concatenates them:
[4, None, "foo"] + [7, 8, (2, 3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [52]:
#If you have a list already defined, you can append multiple elements to it using theextend method:
x = [4, None, "foo"]
x.extend([7, 8, (2, 3)])
x

[4, None, 'foo', 7, 8, (2, 3)]

#### Sort
You can sort a list in place (without creating a new object) by calling its sort
function:


In [53]:
a = [7, 2, 5, 1, 3]
a.sort()
a

[1, 2, 3, 5, 7]

In [56]:
b = ["saw", "small", "He", "foxes", "six"]
b.sort(key=len)
b

['He', 'saw', 'six', 'small', 'foxes']

#### Slicing
You can select sections of most sequence types by using slice notation, which in its
basic form consists of start:stop passed to the indexing operator []:

In [58]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[2:6]

[3, 7, 5, 6]

In [60]:
seq[3:5] = [7,1]
seq

[7, 2, 3, 7, 1, 6, 0, 1]

In [62]:
print(seq[:3])
print(seq[-4:])
print(seq[-6:-2])

[7, 2, 3]
[1, 6, 0, 1]
[3, 7, 1, 6]


In [65]:
#A step can also be used after a second colon to, say, take every other element:
print(seq[::3])
#A clever use of this is to pass -1, which has the useful effect of reversing a list or tuple:
seq[::-1]

[7, 7, 0]


[1, 0, 6, 1, 7, 3, 2, 7]

### Dictionary
The dictionary or dict may be the most important built-in Python data structure.
In other programming languages, dictionaries are sometimes called hash maps or
associative arrays. A dictionary stores a collection of key-value pairs, where key and
value are Python objects. Each key is associated with a value so that a value can
be conveniently retrieved, inserted, modified, or deleted given a particular key. One
approach for creating a dictionary is to use curly braces {} and colons to separate
keys and values:

In [67]:
empty_dict = {}
d1 = {"a": "some value", "b": [1, 2, 3, 4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [68]:
#You can access, insert, or set elements using the same syntax
d1[7] = "an integer"
print(d1)
d1["b"]

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}


[1, 2, 3, 4]

In [69]:
#You can check if a dictionary contains a key using the same syntax
"b" in d1

True

In [71]:
d1[5] = "some value"
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [72]:
d1["dummy"] = "another value"
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 5: 'some value',
 'dummy': 'another value'}

In [73]:
#You can delete values using either the del keyword or the pop method
del d1[5]
print(d1)
ret = d1.pop("dummy")
print(ret)
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 'dummy': 'another value'}
another value


{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [76]:
print("Keys of dictionary d1: ", list(d1.keys()))
print("Values of dictionary d1: ", list(d1.values()))

Keys of dictionary d1:  ['a', 'b', 7]
Values of dictionary d1:  ['some value', [1, 2, 3, 4], 'an integer']


In [77]:
#If you need to iterate over both the keys and values, you can use the items method to
#iterate over the keys and values as 2-tuples:
list(d1.items())

[('a', 'some value'), ('b', [1, 2, 3, 4]), (7, 'an integer')]

In [78]:
# You can merge one dictionary into another using the update method:
d1.update({"b": "foo", "c": 12})
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

#### Creating dictionaries from sequences

In [81]:
#Code that you want to pair up element-wise in a dictionary.
mapping = {}
for key, value in zip(key_list, value_list):
  mapping[key] = value

In [80]:
tuples = zip(range(5), reversed(range(5)))
tuples

In [81]:
mapping = dict(tuples)
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

#### Default values

In [ ]:
#It’s common to have logic like:
if key in some_dict:
  value = some_dict[key]
else:
  value = default_value
#Thus, the dictionary methods get and pop can take a default value to be returned,
value = some_dict.get(key, default_value)

In [82]:
#You could imagine categorizing a list of
#words by their first letters as a dictionary of lists:
words = ["apple", "bat", "bar", "atom", "book"]
by_letter = {}
for word in words:
  letter = word[0]
  if letter not in by_letter:
    by_letter[letter] = [word]
  else:
    by_letter[letter].append(word)

by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [84]:
#The setdefault dictionary method can be used to simplify this workflow.
by_letter = {}
for word in words:
  letter = word[0]
  by_letter.setdefault(letter, []).append(word)
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [85]:
#The built-in collections module has a useful class, defaultdict,
from collections import defaultdict
by_letter = defaultdict(list)
for word in words:
  by_letter[word[0]].append(word)
by_letter

defaultdict(list, {'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']})

#### Valid dictionary key types
While the values of a dictionary can be any Python object, the keys generally have to
be immutable objects like scalar types (int, float, string) or tuples (all the objects in
the tuple need to be immutable, too). The technical term here is hashability. You can
check whether an object is hashable (can be used as a key in a dictionary) with the
hash function:

In [86]:
print(hash("string"))
print(hash((1, 2, (2, 3))))
print(hash((1, 2, [2, 3])))

7018702852872777500
-9209053662355515447


TypeError: unhashable type: 'list'

In [87]:
#To use a list as a key, one option is to convert it to a tuple, which can be hashed as
#long as its elements also can be:
d = {}
d[tuple([1, 2, 3])] = 5
d

{(1, 2, 3): 5}

### Set
A set is an unordered collection of unique elements.

In [88]:
print(set([2, 2, 2, 1, 3, 3]))
{2, 2, 2, 1, 3, 3}

{1, 2, 3}


{1, 2, 3}

In [90]:
#Sets support mathematical set operations like union, intersection, difference, and symmetric difference.
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}
#union
print(a.union(b))
print(a | b)
#intersection
print(a.intersection(b))
print(a & b)

{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 3, 4, 5, 6, 7, 8}
{3, 4, 5}
{3, 4, 5}


In [92]:
# For very large sets, this may be more efficient:
c = a.copy()
c |= b
print(c)
d = a.copy()
d &= b
print(d)

{1, 2, 3, 4, 5, 6, 7, 8}
{3, 4, 5}


In [93]:
#Like dictionary keys, set elements generally must be immutable, and they must be
# hashable. In order to store list-like elements (or other mutable sequences) in a set, you can convert
# them to tuples:
my_data = [1, 2, 3, 4]
my_set = {tuple(my_data)}
my_set

{(1, 2, 3, 4)}

In [94]:
# also check if a set is a subset of (is contained in) or a superset of (contains all
# elements of) another set:
a_set = {1, 2, 3, 4, 5}
print({1, 2, 3}.issubset(a_set))
a_set.issuperset({1, 2, 3})

True


True

In [96]:
# Sets are equal if and only if their contents are equal:
{1, 3, 2} == {2, 1, 3}

True

### Built-In Sequence Functions
Python has a handful of useful sequence functions that you should familiarize your‐
self with and use at any opportunity.

#### enumerate
It’s common when iterating over a sequence to want to keep track of the index of the
current item.

In [ ]:
index = 0
for value in collection:
# do something with value
  index += 1

In [ ]:
# Python has a built-in function, enumerate, which returns a
# sequence of (i, value) tuples:
for index, value in enumerate(collection):
# do something with value

#### sorted

In [97]:
print(sorted([7, 1, 2, 6, 0, 3, 2]))
print(sorted("horse race"))

[0, 1, 2, 2, 3, 6, 7]
[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']


#### zip
zip “pairs” up the elements of a number of lists, tuples, or other sequences to create a
list of tuples:

In [98]:
seq1 = ["foo", "bar", "baz"]
seq2 = ["one", "two", "three"]
zipped = zip(seq1, seq2)
list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [99]:
# zip can take an arbitrary number of sequences, and the number of elements it
# produces is determined by the shortest sequence:
seq3 = [False, True]
list(zip(seq1, seq2, seq3))

[('foo', 'one', False), ('bar', 'two', True)]

In [101]:
for index, (a, b) in enumerate(zip(seq1, seq2)):
  print(f"{index}: {a}, {b}")

0: foo, one
1: bar, two
2: baz, three


#### reversed

In [102]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

### List, Set, and Dictionary Comprehensions
List comprehensions are a convenient and widely used Python language feature. They
allow you to concisely form a new list by filtering the elements of a collection,
transforming the elements passing the filter into one concise expression. They takethe basic form:

*[expr for value in collection if condition]*

the following for loop:

    result = []
    for value in collection:
      if condition:
        result.append(expr)

In [2]:
strings = ["a", "as", "bat", "car", "dove", "python"]
[x.upper() for x in strings if len(x) > 3]

['DOVE', 'PYTHON']

A dictionary comprehension looks like this:

    dict_comp = {key-expr: value-expr for value in collection if condition}

A set comprehension looks like the equivalent list comprehension except with curly
braces instead of square brackets:

    set_comp = {expr for value in collection if condition}

In [3]:
# set comprehension
unique_lengths = {len(x) for x in strings}
print(unique_lengths)
# using map function
set(map(len, strings))

{1, 2, 3, 4, 6}


{1, 2, 3, 4, 6}

In [4]:
loc_mapping = {value: index for index, value in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

#### Nested list comprehensions

In [5]:
all_data = [["John", "Emily", "Michael", "Mary", "Steven"],
            ["Maria", "Juan", "Javier", "Natalia", "Pilar"]]

names_of_interest = []
for names in all_data:
    enough_as = [name for name in names if name.count("a") >= 2]
    names_of_interest.extend(enough_as)

names_of_interest

['Maria', 'Natalia']

In [6]:
result = [name for names in all_data for name in names
                    if name.count("a") >= 2]
result

['Maria', 'Natalia']

Here is another example where we
“flatten” a list of tuples of integers into a simple list of integers:

In [7]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

        flattened = []
        for tup in some_tuples:
            for x in tup:
                flattened.append(x)

In [8]:
[[x for x in tup] for tup in some_tuples]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## 3.2 Functions

Functions are the primary and most important method of code organization and reuse in Python. As a rule of thumb, if you anticipate needing to repeat the same or very similar code more than once, it may be worth writing a reusable function.

In [9]:
def my_function(x, y):
    return x + y

In [10]:
my_function(3, 5)

8

In [11]:
result = my_function(3, 5)
result

8

There is no issue with having multiple return statements. If Python reaches the end of a function without encountering a return statement, None is returned automati‐
cally.

In [12]:
def function_without_return(x):
    print(x)
result = function_without_return("hello!")

hello!


In [13]:
print(result)

None


Each function can have positional arguments and keyword arguments. Keyword argu‐ments are most commonly used to specify default values or optional arguments.

In [14]:
def my_function2(x, y, z=1.5):
    if z > 1:
        return z * (x + y)
    else:
        return z / (x + y)

In [16]:
print(my_function2(3, 5, z=0.7))
print(my_function2(3.14, 7, 3.5))

0.0875
35.49


In [17]:
my_function2(10, 20)

45.0

### Namespaces, Scope, and Local Functions

the function in higher (or even global) scopes. An alternative and more descriptive name describing a variable scope in Python is a namespace. Any variables that are assigned within a function by default are assigned to the local namespace. The local namespace is created when the function is called and is immediately populated by the function’s arguments. After the function is finished, the local namespace is destroyed

In [23]:
def func():
    a = []
    for i in range(5):
        a.append(i)

When func() is called, the empty list a is created, five elements are appended, and then a is destroyed when the function exits.

In [24]:
a = []
def func():
    for i in range(5):
        a.append(i)

In [26]:
#Each call to func will modify list a:
func()
a

func()
a

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [28]:
a = None

def bind_a_variable():
    global a
    a = []
bind_a_variable()


print(a)

[]


### Returning Multiple Values

In [29]:
def f():
    a = 5
    b = 6
    c = 7
    return a, b, c

a, b, c = f()

What’s happening here is that the function is actually just returning one object, a tuple, which is then being unpacked into the result variables.

In [31]:
return_value = f()
print(return_value)

(5, 6, 7)


In [32]:
def f():
    a = 5
    b = 6
    c = 7
    return {"a" : a, "b" : b, "c" : c}

### Functions Are Objects

Since Python functions are objects, many constructs can be easily expressed that are difficult to do in other languages.

In [33]:
states = [" Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
            "south carolina##", "West virginia?"]

One way to do this is to use built-in string methods
along with the re standard library module for regular expressions:

In [34]:
import re
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub("[!#?]", "", value)
        value = value.title()
        result.append(value)
    return result
result = clean_strings(states)
print(result)

['Alabama', 'Georgia', 'Georgia', 'Georgia', 'Florida', 'South Carolina', 'West Virginia']


An alternative approach that you may find useful is to make a list of the operations you want to apply to a particular set of strings:

In [37]:
def remove_punctuation(value):
    return re.sub("[!#?]", "", value)

clean_ops = [str.strip, remove_punctuation, str.title]

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for func in ops:
            value = func(value)
        result.append(value)
    return result

Then we have the following:

In [38]:
clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

You can use functions as arguments to other functions like the built-in map function, which applies a function to a sequence of some kind:

In [39]:
for x in map(remove_punctuation, states):
    print(x)

 Alabama 
Georgia
Georgia
georgia
FlOrIda
south carolina
West virginia


### Anonymous (Lambda) Functions

In [40]:
#option 1
def short_function(x):
    return x * 2  
#option 2
equiv_anon = lambda x: x * 2  
#option 3
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

ints = [4, 0, 1, 5, 6]
apply_to_list(ints, lambda x: x * 2)

[8, 0, 2, 10, 12]

You could also have written *[x * 2 for x in ints]*, but here we were able to succinctly pass a custom operator to the apply_to_list function.

In [41]:
strings = ["foo", "card", "bar", "aaaa", "abab"]
strings.sort(key=lambda x: len(set(x)))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

### Generators
Many objects in Python support iteration, such as over objects in a list or lines in a
file. This is accomplished by means of the iterator protocol, a generic way to make
objects iterable.

In [42]:
some_dict = {"a": 1, "b": 2, "c": 3}
for key in some_dict:
    print(key)

a
b
c


In [43]:
dict_iterator = iter(some_dict)
dict_iterator

In [44]:
list(dict_iterator)

['a', 'b', 'c']

To create a generator, use the yield
keyword instead of return in a function:

In [46]:
def squares(n=10):
    print(f"Generating squares from 1 to {n ** 2}")
    for i in range(1, n + 1):
        yield i ** 2

gen = squares()
gen

<generator object squares at 0x000001D1F5619460>

In [48]:
for x in gen:
    print(x, end=" ")
#Generating squares from 1 to 100

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

#### Generator expressions
Another way to make a generator is by using a generator expression. This is a genera‐
tor analogue to list, dictionary, and set comprehensions.

In [49]:
gen = (x ** 2 for x in range(100))
gen

<generator object <genexpr> at 0x000001D1F55A2DC0>

In [51]:
def _make_gen():
    for x in range(100):
        yield x ** 2
gen = _make_gen()
gen

<generator object _make_gen at 0x000001D1F4EBF640>

In [54]:
print(sum(x ** 2 for x in range(100)))
dict((i, i ** 2) for i in range(5))

328350


{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

#### itertools module
The standard library itertools module has a collection of generators for many
common data algorithms. For example, groupby takes any sequence and a function,
grouping consecutive elements in the sequence by return value of the function.

In [55]:
import itertools
def first_letter(x):
    return x[0]
names = ["Alan", "Adam", "Wes", "Will", "Albert", "Steven"]

for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names)) # names is a generator

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


### Errors and Exception Handling
Handling Python errors or exceptions gracefully is an important part of building
robust programs. In data analysis applications, many functions work only on certain
kinds of input.

In [56]:
float("1.2345")

1.2345

In [57]:
float("hello")

ValueError: could not convert string to float: 'hello'

Suppose we wanted a version of float that fails gracefully, returning the input
argument.

In [58]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return x

In [59]:
print(attempt_float("1.2345"))
print(attempt_float("hello"))

1.2345
hello


In [60]:
float((1, 2))

TypeError: float() argument must be a string or a real number, not 'tuple'

You might want to suppress only ValueError, since a TypeError (the input was not a
string or numeric value) might indicate a legitimate bug in your program. To do that,
write the exception type after except:

In [61]:
def attempt_float(x):
    try:
        return float(x)
    except ValueError:
        return x
    
attempt_float((1, 2))

TypeError: float() argument must be a string or a real number, not 'tuple'

You can catch multiple exception types by writing a tuple of exception types instead

In [63]:
def attempt_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return x
    
attempt_float((1, 2))

(1, 2)

use finally

In [ ]:
f = open("README.md", mode="w")
try:
    write_to_file(f)
finally:
    f.close()

In [ ]:
f = open("README.md", mode="w")
try:
    write_to_file(f)
except:
    print("Failed")
else:
    print("Succeeded")
finally:
    f.close()

#### Exceptions in IPython
If an exception is raised while you are %run-ing a script or executing any statement,
IPython will by default print a full call stack trace (traceback) with a few lines of
context around the position at each point in the stack:

In [65]:
%run examples/ipython_bug.py

Exception: File `'examples/ipython_bug.py'` not found.

## 3.3 Files and the Operating System
To open a file for reading or writing, use the built-in open function with either a
relative or absolute file path and an optional file encoding:

In [85]:
path = "C:\\Users\\Admin\\SGU Document\\Tài liệu ôn thi\\PHAO CỨU SINH MÔN JAVA.docx"
f = open(path, encoding="utf-8")

In [ ]:
lines = [x.rstrip() for x in open(path, encoding="utf-8")]
lines
f.close()

In [ ]:
# One of the ways 
with open(path, encoding="utf-8") as f:
    lines = [x.rstrip() for x in f]

In [ ]:
f1 = open(path)
f1.read(10)
f2 = open(path, mode="rb") # Binary mode
f2.read(10)

In [ ]:
f1.tell()
f2.tell()

In [90]:
import sys
sys.getdefaultencoding()

'utf-8'

In [ ]:
f1.seek(3)
f1.read(1)
f1.tell()

Lastly, we remember to close the files:

In [ ]:
f1.close()
f2.close()

To write text to a file, you can use the file’s write or writelines methods. For
example, we could create a version of PHAO CỨU SINH MÔN JAVA.docx with no blank lines
like so:

In [93]:
path

'C:\\Users\\Admin\\SGU Document\\Tài liệu ôn thi\\PHAO CỨU SINH MÔN JAVA.docx'

In [ ]:
with open("tmp.txt", mode="w") as handle:
    handle.writelines(x for x in open(path) if len(x) > 1)

with open("tmp.txt") as f:
    lines = f.readlines()
lines

### Bytes and Unicode with Files
The default behavior for Python files (whether readable or writable) is text mode,
which means that you intend to work with Python strings (i.e., Unicode). This
contrasts with binary mode, which you can obtain by appending b to the file mode.

In [ ]:
with open(path) as f:
    chars = f.read(10)
chars

len(chars)

In [ ]:
with open(path, mode="rb") as f:
    data = f.read(10)
data

In [ ]:
data.decode("utf-8")
data[:4].decode("utf-8")

Text mode, combined with the encoding option of open, provides a convenient way
to convert from one Unicode encoding to another:

In [ ]:
sink_path = "sink.txt"

with open(path) as source:
    with open(sink_path, "x", encoding="iso-8859-1") as sink:
        sink.write(source.read())

with open(sink_path, encoding="iso-8859-1") as f:
    print(f.read(10))

In [ ]:
f = open(path, encoding='utf-8')
f.read(5)
f.seek(4)
f.read(1)
f.close()

## 3.4 Conclusion

# CHAPTER 4: 
---
## NumPy Basics: Arrays and Vectorized Computation

In [95]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [96]:
# Now let’s multiply each sequence by 2:
%timeit my_arr2 = my_arr * 2

1.14 ms ± 58.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [97]:
%timeit my_list2 = [x * 2 for x in my_list]

50 ms ± 1.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


NumPy-based algorithms are generally 10 to 100 times faster (or more) than their
pure Python counterparts and use significantly less memory.

## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [98]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [99]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [100]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [101]:
data.shape

(2, 3)

In [102]:
data.dtype

dtype('float64')

### Creating ndarrays

In [103]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [104]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print(arr1.dtype)


2
(2, 4)
int32
float64


To create a higher dimensional array
with these methods, pass a tuple for the shape:

In [106]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [108]:
np.empty((2, 3, 2))

array([[[6.95328437e-310, 9.88753912e-312],
        [2.96439388e-323, 9.88753912e-312],
        [1.11260619e-306, 9.88753912e-312]],

       [[4.22757997e-090, 0.00000000e+000],
        [9.88753912e-312, 9.88753912e-312],
        [9.88753912e-312, 0.00000000e+000]]])

**numpy.arange** is an array-valued version of the built-in Python range function:

In [109]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays
The data type or dtype is a special object containing the information (or metadata,
data about data) the ndarray needs to interpret a chunk of memory as a particular
type of data:

In [111]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [113]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr)
float_arr.dtype

int32
[1. 2. 3. 4. 5.]


dtype('float64')

In this example, integers were cast to floating point. If I cast some floating-point
numbers to be of integer data type, the decimal part will be truncated:

In [114]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [115]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

You can also use another array’s dtype attribute:

In [116]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [117]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Arithmetic with NumPy Arrays
Arrays are important because they enable you to express batch operations on data
without writing any for loops. NumPy users call this vectorization. Any arithmetic
operations between equal-size arrays apply the operation element-wise:

In [119]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)

print(arr * arr)
print(arr - arr)
print(1 / arr)
print(arr ** 0.5)


[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr2 > arr)

[[False  True False]
 [ True False  True]]


### Basic Indexing and Slicing

In [122]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [123]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr)

[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]


The “bare” slice [:] will assign to all values in an array:

In [124]:
arr_slice[:] = 64
print(arr)

[ 0  1  2  3  4 64 64 64  8  9]


With higher dimensional arrays, you have many more options. In a two-dimensional
array, the elements at each index are no longer scalars but rather one-dimensional
arrays:

In [125]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0, 2])

[7 8 9]
3
3


In [126]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d[0])
print(arr3d[1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [127]:
old_values = arr3d[0].copy()
arr3d[0] = 42   
print(arr3d)
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Similarly, arr3d[1, 0] gives you all of the values whose indices start with (1, 0),
forming a one-dimensional array:

In [128]:
arr3d[1,0]

array([7, 8, 9])

In [129]:
x = arr3d[1]
print(x)
y = x[0]
print(y)

[[ 7  8  9]
 [10 11 12]]
[7 8 9]


#### Indexing with slices
Like one-dimensional objects such as Python lists, ndarrays can be sliced with the
familiar syntax:

In [130]:
print(arr)
print(arr[1:6])

print(arr2d)
print(arr2d[:2])
print(arr2d[:2, 1:])

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [134]:
lower_dim_slice = arr2d[1, :2]
print(lower_dim_slice.shape)
print(arr2d[:2, 2])
print(arr2d[ : , :1])
arr2d[:2, 1:] = 0
print(arr2d)

(2,)
[3 6]
[[1]
 [4]
 [7]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


### Boolean Indexing

In [136]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


Suppose each name corresponds to a row in the data array and we wanted to
select all the rows with the corresponding name "Bob".

In [137]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [ ]:
# This Boolean array can be passed when indexing the array:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In these examples, I select from the rows where names == "Bob" and index the
columns, too:

In [139]:
print(data[names == "Bob", 1:])
print("---------------")
print(data[names == "Bob", 1])
print("---------------")
mask = (names != "Bob")
print(mask)
print("---------------")
print(~(names == "Bob"))
print("---------------")
print(data[mask])

[[7]
 [0]]
---------------
[7 0]
---------------
[False  True  True False  True  True  True]
---------------
[False  True  True False  True  True  True]
---------------
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


The ~ operator can be useful when you want to invert a Boolean array referenced by a
variable:

In [140]:
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

To select two of the three names to combine multiple Boolean conditions, use
Boolean arithmetic operators like & (and) and | (or):

In [141]:
mask = (names == "Bob") | (names == "Will")
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]


In [142]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [143]:
# You can also set whole rows or columns using a one-dimensional Boolean array:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

### Fancy Indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.


In [144]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [146]:
# To select a subset of the rows in a particular order, you can simply pass a list or 
# ndarray of integers specifying the desired order:
arr[[4, 3, 0, 6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [147]:
# Hopefully this code did what you expected! Using negative indices selects rows from
# the end:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [152]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print("---------------")
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
print("---------------")
arr[[1,5,7,2], [0,3,1,2]] = 0
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
---------------
[ 4 23 29 10]
---------------
[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]]


### Transposing Arrays and Swapping Axes
Transposing is a special form of reshaping that similarly returns a view on the
underlying data without copying anything.

In [ ]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print("---------------")
# Simple transposing with .T is a special case of swapping axes. ndarray has the method
#swapaxes
print(arr.T)
print("---------------")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
---------------


In [ ]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)
print("---------------")
print(np.dot(arr.T, arr))
print("---------------")
# The @ infix operator is another way to do matrix multiplication:
print(arr.T @ arr)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
---------------
[[39 20 12]
 [20 14  2]
 [12  2 10]]
---------------
[[39 20 12]
 [20 14  2]
 [12  2 10]]


In [155]:
print(arr)
print(arr.swapaxes(0, 1))

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]


## 4.2 Pseudorandom Number Generation